import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import JsBarcode from 'jsbarcode';
import {ArrowRight, Barcode, Check, CheckCircle2, ChevronDown, ExternalLink, Info, LoaderCircle, ScanLine, Search, ShieldCheck, X} from 'lucide-react';
import type {Result} from '@barcodebridge/core';
import './style.css';
type Reply={query:{kind:string;value:string;nameHint?:string};results:Result[];providerErrors:string[];needsNameHint:boolean};
function BarcodeArt({value,format,large=false}:{value:string;format:Result['format'];large?:boolean}) {
 const ref=useRef<SVGSVGElement>(null);
 useEffect(()=>{if(ref.current)try{JsBarcode(ref.current,value,{format:format==='EAN-13'?'EAN13':format==='EAN-8'?'EAN8':'UPC',displayValue:true,font:'monospace',fontSize:large?22:16,width:large?3:2,height:large?118:76,margin:12,background:'#ffffff',lineColor:'#142045'});}catch{}},[value,format,large]);
 return <svg ref={ref} role="img" aria-label={`Codice a barre ${format}: ${value}`} className="barcode-svg"/>;
}
function App(){
 const [input,setInput]=useState(''); const [hint,setHint]=useState('');const [loading,setLoading]=useState(false);
 const [data,setData]=useState<Reply|null>(null);const [error,setError]=useState('');const [selected,setSelected]=useState(0);const [scan,setScan]=useState(false);
 const asin=/^(?:B[A-Z0-9]{9}|https?:\/\/[^\s]*amazon\.[^\s]+\/[^\s]+)$/i.test(input.trim());
 async function submit(e:React.FormEvent){e.preventDefault();if(!input.trim())return;setLoading(true);setError('');setData(null);setSelected(0);
 try{const res=await fetch('/api/resolve',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input:input.trim(),nameHint:hint.trim()})});const json=await res.json();if(!res.ok)throw new Error(json.error||'Impossibile completare la ricerca');setData(json);}catch(err){setError((err as Error).message)}finally{setLoading(false)} }
 const product=data?.results[selected];
 useEffect(()=>{if(!scan)return;const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')setScan(false)};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler)},[scan]);
 return <><header className="topbar"><a href="/" className="brand"><span className="brand-icon"><Barcode size={23} strokeWidth={2.4}/></span><span>barcode<span className="brand-accent">bridge</span></span></a><span className="top-note"><span className="top-dot"/> OPEN SOURCE PROJECT · V0.1</span><span className="top-link">MIT LICENSE <ExternalLink size={14}/></span></header>
 <main><div className="hero"><div className="eyebrow"><span className="spark">✦</span> DAL PRODOTTO AL CODICE A BARRE</div><h1>Il barcode che cerchi,<br/><em>senza cercare ovunque.</em></h1><p className="subtitle">Incolla un ASIN, un link Amazon o il nome di un prodotto. BarcodeBridge cerca i codici possibili, verifica le fonti e li rende pronti da scansionare.</p></div>
 <section className="search-card" aria-label="Cerca un prodotto"><form onSubmit={submit}><label htmlFor="product-input">CERCA UN PRODOTTO</label><div className="search-row"><Search size={22} className="search-icon"/><input id="product-input" placeholder="ASIN, URL Amazon o nome prodotto…" value={input} onChange={e=>setInput(e.target.value)} autoComplete="off"/><button type="submit" disabled={loading||!input.trim()}>{loading?<LoaderCircle size={18} className="spin"/>:<><span>Cerca barcode</span><ArrowRight size={18}/></>}</button></div>{asin&&<div className="hint-row"><Info size={16}/><span>Hai il nome del prodotto? Aggiungilo per trovare risultati più precisi.</span><input aria-label="Nome del prodotto (opzionale)" placeholder="Es. siero viso acido ialuronico 100 ml" value={hint} onChange={e=>setHint(e.target.value)}/></div>}</form><div className="try-row"><span>PROVA CON</span><button onClick={()=>{setInput('B09SY5QHHJ');setHint('Luminer Cosmetics Siero Acido Ialuronico 100 ml')}}>B09SY5QHHJ <ArrowRight size={13}/></button><button onClick={()=>{setInput('Nutella Ferrero 750 g');setHint('')}}>Nutella 750 g <ArrowRight size={13}/></button></div></section>
 {error&&<div className="notice error" role="alert">{error}</div>}
 {data&&<section className="results"><div className="section-head"><div><span className="mini-label">RISULTATI DELLA RICERCA</span><h2>{data.results.length?`${data.results.length} codic${data.results.length===1?'e trovato':'i trovati'}`:'Nessun codice affidabile trovato'}</h2></div><span className="search-for">Per “{data.query.value}”</span></div>
 {data.needsNameHint&&<div className="notice"><Info size={18}/><span>Nessuna fonte disponibile ha collegato questo ASIN a un barcode. Inserisci nome e formato esatti, oppure configura una fonte di ricerca per ASIN sul server.</span></div>}
 {!data.results.length&&<div className="empty"><ScanLine size={34}/><h3>Non abbiamo una corrispondenza da mostrarti.</h3><p>Prova con marca, nome e formato esatto. Un codice valido da solo non prova che appartenga al prodotto cercato.</p></div>}
 {product&&<div className="result-layout"><div className="result-main"><div className="result-header"><span className="candidate">CANDIDATO {selected+1} DI {data.results.length}</span><span className={`confidence ${product.confidence}`}><span className="status-dot"/>{product.confidence==='high'?'Corrispondenza forte':product.confidence==='medium'?'Da verificare':'Corrispondenza debole'}</span></div><h3>{product.title||'Prodotto senza nome'}</h3><p className="product-meta">{[product.brand,product.quantity].filter(Boolean).join(' · ')||'Controlla il nome e la confezione prima di scansionare'}</p><div className="barcode-area"><div className="barcode-top"><span>CODICE {product.format}</span><span className="valid"><CheckCircle2 size={16}/> Checksum valido</span></div><BarcodeArt value={product.gtin} format={product.format}/></div><div className="result-actions"><button className="primary-action" onClick={()=>setScan(true)}><ScanLine size={18}/> Modalità scansione <ArrowRight size={17}/></button><button className="text-action" onClick={()=>navigator.clipboard.writeText(product.gtin)}><Check size={16}/> Copia codice</button></div></div><aside className="evidence"><div className="evidence-title"><ShieldCheck size={21}/><h3>Perché questo risultato?</h3></div><p>Controlla le prove prima di usare il codice. La cifra di controllo conferma solo che il numero è strutturalmente valido.</p><ul>{product.reasons.map(r=><li key={r}><CheckCircle2 size={17}/>{r}</li>)}</ul><div className="sources"><span>FONTI · {product.evidence.length}</span>{product.evidence.map((source,i)=><a key={`${source.provider}-${i}`} href={source.url} target="_blank" rel="noreferrer"><span>{source.provider}<small>{source.title}{source.checkedOn?` · controllata il ${source.checkedOn}`:''}</small></span><ExternalLink size={15}/></a>)}</div></aside></div>}
 {data.results.length>1&&<div className="alternatives"><h3>Altri codici possibili</h3>{data.results.map((r,i)=>i!==selected&&<button key={`${r.gtin}-${i}`} onClick={()=>setSelected(i)}><span><strong>{r.title||r.gtin}</strong><small>{r.gtin} · {r.format}</small></span><span className={`confidence ${r.confidence}`}>{r.confidence==='high'?'Forte':r.confidence==='medium'?'Da verificare':'Debole'}</span><ChevronDown size={17}/></button>)}</div>}
 {data.providerErrors.length>0&&<details className="provider-errors"><summary>Alcune fonti non hanno risposto ({data.providerErrors.length})</summary><ul>{data.providerErrors.map(x=><li key={x}>{x}</li>)}</ul></details>}
 </section>}
 <section className="how"><div className="how-label">COME FUNZIONA <span/></div><div className="steps"><div><span className="step-number">01</span><h3>Inserisci il prodotto</h3><p>Usa il nome, un codice o il link di una pagina Amazon.</p></div><div><span className="step-number">02</span><h3>Confronta i risultati</h3><p>Vedi il codice, le fonti e i segnali che lo collegano al prodotto.</p></div><div><span className="step-number">03</span><h3>Scansiona dallo schermo</h3><p>Apri il codice a tutto schermo e inquadralo con Yuka o un’altra app.</p></div></div></section></main>
 <footer><span className="footer-brand">barcode<span>bridge</span></span><span>Un ponte tra prodotti e codici. Sorgenti esterne soggette a disponibilità e limiti.</span><span>MIT LICENSE · V0.1</span></footer>
 {scan&&product&&<div className="scan-overlay" role="dialog" aria-modal="true" aria-label="Barcode da scansionare"><button className="close-scan" onClick={()=>setScan(false)} aria-label="Chiudi"><X size={22}/></button><span className="scan-label">INQUADRA IL CODICE CON IL TUO SMARTPHONE</span><div className="scan-paper"><BarcodeArt value={product.gtin} format={product.format} large/></div><strong>{product.title}</strong><p>{product.confidence==='low'?'Corrispondenza debole: verifica il prodotto prima di usarlo.':'Assicurati che marca e formato corrispondano alla confezione.'}</p><span className="escape-hint">PREMI ESC PER CHIUDERE</span></div>}
 </>;
}
createRoot(document.getElementById('root')!).render(<App/>);
